version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-db
    networks:
      - default
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 6

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    image: listmonk/listmonk:latest
    env_file:
      - .env
    environment:
      - LISTMONK_app__address=0.0.0.0:9000
      - LISTMONK_app__admin_username=${LISTMONK_ADMIN_USERNAME:-}
      - LISTMONK_app__admin_password=${LISTMONK_ADMIN_PASSWORD:-}
      - LISTMONK_db__host=db
      - LISTMONK_db__port=5432
      - LISTMONK_db__database=${POSTGRES_DB}
      - LISTMONK_db__user=${POSTGRES_USER}
      - LISTMONK_db__password=${POSTGRES_PASSWORD}
      - LISTMONK_db__ssl_mode=disable
      - LISTMONK_db__max_open=25
      - LISTMONK_db__max_idle=25
      - LISTMONK_db__max_lifetime=300s
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 6

networks:
  default:
    external:
      name: ${COMPOSE_PROJECT_NAME}
